awards/awardsapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("web.urls"))]

awards/web/urls.py
from django.urls import path
from .views import (
    LoginKeyCheckView,
    IndexView,
    SubmissionsView,
    StaffSubmissionsView,
    EntryView,
    StaffIndexView,
    UserListView,
    EntryAssignUser,
    AssignmentView,
    ExportReviews,
    custom_logout,
)


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("login/<str:key>/", LoginKeyCheckView.as_view(), name="login-key-check"),
    path("submissions/", SubmissionsView.as_view(), name="submissions"),
    path(
        "submissions/<int:pk>/<int:user_id>/",
        EntryAssignUser.as_view(),
        name="entry-assign-user",
    ),
    path("submissions/<int:pk>/", EntryView.as_view(), name="entry-detail"),
    path("staff/", StaffIndexView.as_view(), name="staff-index"),
    path(
        "staff/submissions/", StaffSubmissionsView.as_view(), name="staff-submissions"
    ),
    path("staff/users/", UserListView.as_view(), name="staff-user-list"),
    path("staff/assignment/", AssignmentView.as_view(), name="staff-assignment"),
    path("staff/export/", ExportReviews.as_view(), name="staff-export"),
    path("staff/logout/", custom_logout, name="custom-logout"),
    path("", IndexView.as_view(), name="index"),
]

awards/web/models.py
import statistics
import uuid

from django.core.mail import EmailMessage
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse

from constance import config

from .utils_gform import GForm


class Category(models.Model):
    name = models.CharField(max_length=120)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Entry(models.Model):
    title = models.TextField()
    entry_id = models.IntegerField(null=True)

    category = models.ForeignKey(
        Category, blank=True, null=True, on_delete=models.CASCADE
    )
    subcategory = models.CharField(max_length=125, blank=True)

    material = models.TextField(blank=True, null=True)
    video = models.TextField(blank=True, null=True)
    slideshare = models.TextField(blank=True, null=True)

    data = JSONField(blank=True, null=True)

    class Meta:
        verbose_name = "Entry"
        verbose_name_plural = "Entries"

    def __str__(self):
        return "#{} - {}".format(self.entry_id, self.title)

    def conflicts(self):
        return self.rating_set(manager="conflicts")

    def dones(self):
        return self.rating_set(manager="dones")

    def drafts(self):
        return self.rating_set(manager="drafts")

    def get_reviewers(self):
        reviewers = []
        for user in User.objects.filter(is_staff=False, is_active=True).order_by(
            "first_name"
        ):
            reviewers.append(
                {
                    "user": user,
                    "assigned": self.rating_set.filter(
                        user=user, status__in=["empty", "draft", "conflict"]
                    ).exists(),
                }
            )
        return reviewers

    def get_entry_link(self):
        if (self.data is None) or (not GForm.KEY_LINK in self.data):
            return "-"
        return self.data.get(GForm.KEY_LINK)

    def get_absolute_url(self):
        return reverse("entry-detail", kwargs={"pk": self.pk})


RATING_CHOICES = (
    ("empty", "Empty ballot"),
    ("draft", "Draft rating"),
    ("conflict", "Conflict of interest or can't understand the language"),
    ("done", "Completed rating"),
)


class DraftsRatingManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status__in=["empty", "draft"])


class DonesRatingManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status__in=["done"])


class ConflictsRatingManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status__in=["conflict"])


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)

    access = models.IntegerField(
        null=True,
        verbose_name="Access",
        help_text="Resources are easily accessible and readily available to anyone.",
    )
    quality = models.IntegerField(
        null=True,
        verbose_name="Quality",
        help_text="Exemplary quality in the presentation of content (in breadth, depth, creativity)",
    )
    visual = models.IntegerField(
        null=True,
        verbose_name="Visual representation",
        help_text="Uses multiple means of visual representation through accessible embedded multimedia content.",
    )
    engagement = models.IntegerField(
        null=True,
        verbose_name="Engagement",
        help_text="Provides multiple means of engagement through social learning connections, networks and/or communities.",
    )
    inclusion = models.IntegerField(
        null=True,
        verbose_name="Inclusion",
        help_text="Promotes inclusiveness and diversity through the use of a variety of languages and cultural contexts.",
    )
    licensing = models.IntegerField(
        null=True,
        verbose_name="Licensing",
        help_text="Copyright and Fair Use guidelines are followed with proper use of citations. An open license is clearly stated.",
    )
    accessibility = models.IntegerField(
        null=True,
        verbose_name="Accessibility",
        help_text="The resource supports learners with diverse needs.",
    )
    currency = models.IntegerField(
        null=True,
        verbose_name="Currency",
        help_text="Information is current and up to date. Date of materials is clearly indicated.",
    )
    individual = models.IntegerField(null=True, verbose_name="Individual Rating")

    comment = models.TextField(blank=True, verbose_name="Comment")

    status = models.CharField(max_length=20, choices=RATING_CHOICES, default="empty")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    drafts = DraftsRatingManager()
    dones = DonesRatingManager()
    conflicts = ConflictsRatingManager()

    def __str__(self):
        return "Rating of #{} by {}".format(self.entry.entry_id, self.user.username)

    @property
    def average(self):
        scores = []
        for item in [
            self.access,
            self.quality,
            self.visual,
            self.engagement,
            self.inclusion,
            self.licensing,
            self.accessibility,
            self.currency,
        ]:
            if item:
                scores.append(item)

        if scores:
            return round(statistics.mean(scores), 2)


class LoginKey(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    key = models.CharField(max_length=32)

    used = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} - {}".format(self.user, self.email)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = uuid.uuid4().hex

        super(LoginKey, self).save(*args, **kwargs)

    def send_email(self):
        body = render_to_string(
            "mail-login/mail_body.txt",
            {"key_max_age": config.LOGIN_KEY_MAX_AGE, "url": self.get_absolute_url()},
        )
        try:
            email = EmailMessage(
                "OE Awards Review login information",
                body,
                "OE Awards Reviews <memberservices@oeglobal.org>",
                [self.email],
                reply_to=["awards@oeglobal.org"],
            )
            email.send()
            print("INFO: email with login information sent to %s" % self.email)
        except (Exception, ConnectionRefusedError) as e:
            print("ERROR: failed to send email with login information: %s" % e)

    def get_absolute_url(self):
        return reverse_lazy("login-key-check", kwargs={"key": self.key})


class Reviewer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_board_member = models.BooleanField(default=False)
    year = models.IntegerField(
        null=True,
        verbose_name="Year",
        help_text="Year when a reviewer is performing reviews.",
    )

awards/web/templates/web-staff/assignment.html
{% extends "base.html" %}{% load cache %}

{% block headtitle %}Interactive assignment{% endblock %}

{% block contents %}
    <h2 class="text-bold text-xl mt-10">Filter by category</h2>
    <ul>
        {% for cat in categories %}
            <li class="inline-block hover:underline"><a
                    href="{% url 'staff-assignment' %}?cat={{ cat.category__id }}">{{ cat.category__name }}</a>
                {% if not forloop.last %}, {% endif %}</li>
        {% endfor %}
    </ul>

    {% if filtering %}
        {% with object_list|first as entry %}
            <h2 class="text-bold text-xl mt-10">{{ entry.category }}</h2>
        {% endwith %}

        {% for entry in object_list %}
            <div class="bg-white shadow overflow-hidden sm:rounded-md mt-6">
                <ul>
                    {% include "_includes/card-excerpt.html" with obj=entry %}
                </ul>
                <div class="px-4 py-4 sm:px-6">
                    {% include "_includes/reviews-control.html" with reviewers=entry.get_reviewers entry=entry %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        {% regroup object_list by category as entry_list %}

        {% for category, entries in entry_list %}
            <h2 class="text-bold text-xl mt-10">{{ category }}</h2>

            {% for entry in entries %}
                <div class="bg-white shadow overflow-hidden sm:rounded-md mt-6">
                    <ul>
                        {% include "_includes/card-excerpt.html" with obj=entry hide_status=True %}
                    </ul>
                    <div class="px-4 py-4 sm:px-6">
                        {% include "_includes/reviews-control.html" with reviewers=entry.get_reviewers entry=entry %}
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
{% endblock %}

awards/web/templates/web-staff/index.html
{% extends "base.html" %}{% load svg %}

{% block headtitle %}Overview{% endblock %}

{% block contents %}
    <div class="lg:w-2/3">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
            Overview
        </h3>
        <div class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-3">
            <div class="bg-white overflow-hidden shadow rounded-lg">
                <div class="px-4 py-5 sm:p-6">
                    <dl>
                        <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
                            Completed reviews
                        </dt>
                        <dd class="mt-1 text-3xl leading-9 font-semibold text-gray-900">
                            {{ dones }}
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow rounded-lg">
                <div class="px-4 py-5 sm:p-6">
                    <dl>
                        <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
                            Waiting for review
                        </dt>
                        <dd class="mt-1 text-3xl leading-9 font-semibold text-gray-900">
                            {{ drafts }}
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow rounded-lg">
                <div class="px-4 py-5 sm:p-6">
                    <dl>
                        <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
                            Skipped reviews
                        </dt>
                        <dd class="mt-1 text-3xl leading-9 font-semibold text-gray-900">
                            {{ conflicts }}
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="lg:w-1/3 mt-10">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
            Actions
        </h3>

        <div class="flex justify-between mt-5">
            <a class="button primary" href="{% url 'staff-assignment' %}">Interactive assignment</a>
            <a class="button secondary" href="{% url 'staff-export' %}">Export Reviews</a>
        </div>
    </div>
{% endblock %}

awards/web/templates/web-staff/submissions.html
{% extends "base.html" %}

{% block headtitle %}Submissions{% endblock %}

{% block contents %}
    {% regroup object_list by category as entry_list %}

    {% for category, entries in entry_list %}
        <h2 class="text-bold text-xl mt-10">{{ category }}</h2>

        <div class="bg-white shadow overflow-hidden sm:rounded-md mt-6">
            <ul>
                {% for obj in entries %}
                    {% include "_includes/card-excerpt.html" with obj=obj %}
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
{% endblock %}

awards/web/templates/web-staff/user_list.html
{% extends "base.html" %}

{% block headtitle %}Reviewers{% endblock %}

{% block contents %}
    <h2 class="text-bold text-xl mt-10">Active Reviewers</h2>

    <div class="bg-white shadow overflow-hidden sm:rounded-md mt-6">
        <ul>
            {% for obj in data %}
                {% include "_includes/user_card-excerpt.html" with obj=obj %}
            {% endfor %}
        </ul>
    </div>
{% endblock %}